[package]
name = "botapi"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.52"
tonic = { version="0.6.2" }
prost = "0.9.0"
prost-types = "0.9.0"

[build-dependencies]
tonic-build = "0.6.2"
