[package]
name = "healthcheck"
version = "0.1.0"
edition = "2021"

[dependencies]
botapi = { version = "1.1.0", git="https://github.com/web-zavod/botapi" }
tonic = "0.6.2"
tokio = { version = "1.15.0", features = ["rt-multi-thread"] }
log = "0.4.8"
env_logger = "0.9.0"
