version: "3.8"
services:
  app:
    build: .
    environment:
      RUST_LOG: debug
    ports:
      - "5000:5000"

  grpcox:
    depends_on:
      - app
    image: gusaul/grpcox
    ports:
      - "6969:6969"

